"""Adição do Tipo de movimentação de transação

Revision ID: 4bb6ed4a7ac8
Revises: 6d0f504ef52a
Create Date: 2026-01-20 09:55:29.159555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb6ed4a7ac8'
down_revision: Union[str, Sequence[str], None] = '6d0f504ef52a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('movment_type', sa.Enum('ENTRADA', 'SAIDA', name='enummovmenttype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'movment_type')
    # ### end Alembic commands ###
