"""Adicionado mais tipos de pagamento

Revision ID: f304d2ac1168
Revises: 90acf570947a
Create Date: 2026-01-22 16:57:44.991683

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f304d2ac1168"
down_revision: Union[str, Sequence[str], None] = "90acf570947a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.alter_column(
            "transaction_type",
            existing_type=sa.VARCHAR(length=1),
            type_=sa.Enum("P", "C", "D", "T", "DP", name="enumpaymenttypes"),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transactions",
        "transaction_type",
        existing_type=sa.Enum("P", "C", "D", "T", "DP", name="enumpaymenttypes"),
        type_=sa.VARCHAR(length=1),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
